// scripts/remix/compile.test.ts
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compileRemix } from './compile';
import { loadDoc, partMeasures } from './structure';

const here = dirname(fileURLToPath(import.meta.url));
const xml = readFileSync(join(here, 'fixtures', 'two-section.musicxml'), 'utf8');

const recipe = (passes: unknown[]) => ({
  songId: 'two-section',
  variantId: 'test-mix',
  name: 'Test mix',
  passes,
});

/** Pitch letters of the compiled output, in order — the form fingerprint. */
const steps = (out: string) =>
  partMeasures(loadDoc(out)).map((m) => m.getElementsByTagName('step')[0]?.textContent ?? '·');

describe('compileRemix', () => {
  it('repeats off: one volta-collapsed pass (skips ending 1, keeps ending 2)', () => {
    const out = compileRemix(xml, recipe([{ repeats: 'off' }]));
    // verse: C then volta-2 E (D is volta 1); chorus once: F G A
    expect(steps(out)).toEqual(['C', 'E', 'F', 'G', 'A']);
  });

  it('as-written: voltas unroll and plain repeats double', () => {
    const out = compileRemix(xml, recipe([{ repeats: 'as-written' }]));
    // verse: C D (volta 1) C E (volta 2); chorus twice: F G A F G A
    expect(steps(out)).toEqual(['C', 'D', 'C', 'E', 'F', 'G', 'A', 'F', 'G', 'A']);
  });

  it('per-section counts and explicit section order', () => {
    const out = compileRemix(xml, recipe([{ sections: ['chorus'], repeats: { chorus: 3 } }]));
    expect(steps(out)).toEqual(['F', 'G', 'A', 'F', 'G', 'A', 'F', 'G', 'A']);
  });

  it('endWith appends a volta-collapsed section', () => {
    const out = compileRemix(xml, recipe([{ repeats: 'off', endWith: 'verse' }]));
    expect(steps(out)).toEqual(['C', 'E', 'F', 'G', 'A', 'C', 'E']);
  });

  it('multiple passes stitch with page breaks and labels; measures renumber 1..N', () => {
    const out = compileRemix(
      xml,
      recipe([
        { label: 'Page 1', repeats: 'off' },
        { label: 'Page 2', repeats: 'off' },
      ]),
    );
    const measures = partMeasures(loadDoc(out));
    expect(measures.map((m) => m.getAttribute('number'))).toEqual(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']);
    // Page break lands on the first measure of pass 2 (index 5), not pass 1.
    const withNewPage = measures
      .map((m, i) => [i, m.getElementsByTagName('print')] as const)
      .filter(([, p]) => Array.from(p).some((pr) => pr.getAttribute('new-page') === 'yes'))
      .map(([i]) => i);
    expect(withNewPage).toEqual([5]);
    expect(out).toContain('>Page 1<');
    expect(out).toContain('>Page 2<');
    // No repeats or endings survive in the flattened chart.
    expect(out).not.toContain('<repeat');
    expect(out).not.toContain('<ending');
    // Final barline closes the chart.
    const last = measures[measures.length - 1];
    expect(last.getElementsByTagName('bar-style')[0]?.textContent).toBe('light-heavy');
  });

  it('lyric selection: verse pick renumbers to line 1; chorus flag gates chorus lyrics', () => {
    const out = compileRemix(xml, recipe([{ repeats: 'off', lyrics: { verse: 2, chorus: true } }]));
    const doc = loadDoc(out);
    const lyrics = Array.from(doc.getElementsByTagName('lyric'));
    // verse measures keep only former line 2 ("two"), renumbered to 1; chorus keeps "la".
    expect(lyrics.map((l) => [l.getAttribute('number'), l.getElementsByTagName('text')[0]?.textContent])).toEqual([
      ['1', 'two'],
      ['1', 'la'],
    ]);
    const off = compileRemix(xml, recipe([{ repeats: 'off', lyrics: 'off' }]));
    expect(off).not.toContain('<lyric');
  });

  it('is deterministic: identical output across runs', () => {
    const r = recipe([{ repeats: 'off', endWith: 'verse' }]);
    expect(compileRemix(xml, r)).toBe(compileRemix(xml, r));
  });

  it('carries a generated-file comment naming the recipe', () => {
    const out = compileRemix(xml, recipe([{ repeats: 'off' }]));
    expect(out).toContain('GENERATED by scripts/remix from remixes/two-section.test-mix.remix.json');
  });
});
